template = ""
rev_id = 6
template_sha = "08de358f84ed88e430f0754209b276aa821f47c5"

[replacements]
__LICENSE__ = ""
__UND2C_SRC__ = "myv"
__UND2C_TRG__ = "de"
__UNDEFINED_SOURCE__ = "Erzya"
__UNDEFINED_TARGET__ = "German"
__UND_SRC__ = "myv"
__UND_TRG__ = "deu"
