template = ""
rev_id = 8
template_sha = "6ead0c8811e460a0145949f88b0d66e31b788c4a"

[replacements]
__LICENSE__ = ""
__UND2C_SRC__ = "myv"
__UND2C_TRG__ = "de"
__UNDEFINED_SOURCE__ = "Erzya"
__UNDEFINED_TARGET__ = "German"
__UND_SRC__ = "myv"
__UND_TRG__ = "deu"
