template = ""
rev_id = 11
template_sha = "211be85371b914c06257b37026553182562f3608"

[replacements]
__LICENSE__ = ""
__UND2C_SRC__ = "myv"
__UND2C_TRG__ = "de"
__UNDEFINED_SOURCE__ = "Erzya"
__UNDEFINED_TARGET__ = "German"
__UND_SRC__ = "myv"
__UND_TRG__ = "deu"
